# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('fork_num', models.IntegerField()),
                ('star_num', models.IntegerField()),
                ('watch_num', models.IntegerField()),
                ('http_link', models.URLField()),
                ('img_link', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
